### ISSUE TITLE
Client Settings

### ISSUE THREAD

**Issue by patrickburk1988** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#10]
This may be outside the purview of this module, but it would be awesome if there were a way to copy/save/import/export not just world settings, but also client settings. If such a thing is even possible, that is, since client settings are presumably stored as cookies?

**(Admittedly Niche) Use Case:**
I regularly access Foundry (hosted with Forge) from both home and my workplace. My workplace computer, specifically, is required to clear all cookies after each use. Firefox, as far as I'm aware, has no real way to export/import specific cookies, so I have no way to easily maintain the same client settings between computers — or even between browser sessions on my work computer. If I had a way to export/import client settings, I could just keep a copy of ```client-settings-export.json``` (or whatever) saved on my work computer and re-import it every browser session.

**Comment by NateHawk85** [comment]
Not sure if this helps or not, but this is something I've actually kept as a script for when my IP address changes. I just run something along the lines of - `localStorage.setItem('core.leftClickRelease', true);`

The developer of this module should be able to pretty easily get the localStorage dictionary and keep track of all values. The only difficult part would be differentiating between Foundry-related ones vs. non-Foundry. That being said, when running on my normal server, I don't see any out-of-place settings that would be harmful to export.

**Comment by sashemi** [comment]
Isn't this module supposed to copy client settings?

Readme:
Non-GM users can only import client-side settings.
