### ISSUE TITLE
JSON Export missing

### ISSUE THREAD

**Issue by rfreeman** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#29]
Using Forien Copy Environment v2.1.3 I no longer have the option to Export as JSON. Foundry v9.269. DnD5e 1.6.2. I disabled all modules except Forien with the same result. Running with NodeJS on Linux.

After comparing the code it appears that the Save As JSON option was removed.

**Comment by sneat** [comment]
Appologies @rfreeman I didn't see the notification for this ticket.

I'm re-adding the functionality in version v2.1.4 - #31

**Comment by sneat** [comment]
I'm interested what the use case you had for that option was though, were you passing it across to another system?

**Comment by rfreeman** [comment]
Yes, I was using it to duplicate the modules I'm using in test environments. I was also exporting the JSON and comparing them for configuration changes.

**Comment by sneat** [comment]
@rfreeman just hoping to get confirmation that the japanese translation is correct prior to releasing it.

Feel free to download it early though by going to https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/tree/2.1.4 and downloading the zip from the green Code button in the top right.

**Comment by sneat** [comment]
Released v2.1.4

If you have any further issues, please open another ticket and assign it to me 👍
