### ISSUE TITLE
Feature Request: time/datestamp the generated settings file on export

### ISSUE THREAD

**Issue by esheyw** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#30]
This could maybe be dealt with by just fiddling with my chrome settings, I just use it for foundry (firefox main), but I think this has value regardless. 

Right now with what I assume is default chrome download handling, the .json gets automatically saved to /users/me/downloads, which is fine, but since the filename is static the folder fills up with:
```
foundry-settings-export.json
foundry-settings-export (1).json
foundry-settings-export (2).json
```
etc on repeated exports, if we could get 
```
foundry-settings-fce-2022-06-19-18-22-36.json
foundry-settings-fce-2022-06-19-18-37-19.json
foundry-settings-fce-2022-06-19-18-55-44.json
```
or similar instead, it'd be handy for a number of reasons I think.

**Comment by sneat** [comment]
Added in v2.1.4
