### ISSUE TITLE
[BUG] Error Exporting game settings : Settings Model Validations Errors

### ISSUE THREAD

**Issue by p4535992** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#35]
**Describe the bug**

I cannot export the settings for a undefined value in some unknown module, but i cannot figure out which module is the culprit.

![imng](https://i.imgur.com/QLILPAF.png)

**To Reproduce**
1. Go to the settings sidebar
2. Right click on the "General Infomation" panel
3. Click "Export Settings"

**Expected behavior**

No exception or at least print the reference to which module is causing this issue.

**Screenshots**

![imng](https://i.imgur.com/QLILPAF.png)

**Browser:**
 - 

**Foundry Version:** 

Core Version: 10.288

**System:** 

System: dnd5e 2.0.3 (Atropos) 

**Additional context**

The full list of modules i'm using:

RWE 1.3.0 (Monkeyy)
about-time 10.0.1 (tposney)
active-effect-manager-lib 0.1.15 (p4535992)
advanced-macros v1.17.3 ()
always-hp 10.3 (IronMonk)
arbron-hp-bar 2.2.4 (Jeff ‘Arbron’ Hitchcock)
autoanimations 4.0.15 (Otigon (Otigon#2010))
automated-evocations-variant 1.6.10 (theripper93, p4535992)
babele 2.3.2 (Simone)
babonus 10.0.9.2 (Zhell)
backpack-manager 10.0.3 (Zhell)
bossbar 1.0.1 (theripper93)
chat-images 3.2 (bmarian)
chat-portrait 0.8.22 (Shoyu Vanilla, p4535992)
colorsettings 2.9.0 (ardittristan#0001)
combat-utility-belt 1.10.3 (Evan Clarke)
compendium-folders 2.5.5 (Erceron)
compendiums-mix-dnd5e-ita-private v1.1.2 (p4535992)
comprehend-languages 1.3 (Meneltamar)
curtain-animations 1.2.0 (enso)
dae 10.0.9 (tposney)
dfreds-convenient-effects 3.0.2 (DFreds)
dice-calculator 1.5.2 (Asacolips)
dnd-randomizer 1.0.15 (theripper93, Mouse0270, thetreat)
drag-all-to-hotbar 1.1.0 (Saif Addin Ellafi)
effective-transferral 1.2.5 (Flix)
flying-tokens 1.3.1 (winterwulf)
forien-copy-environment v2.1.5 (Blair McMillan, Forien)
foundryvtt-arms-reach 2.2.12 (Psyny, p4535992)
foundryvtt-simple-calendar 2.1.40 (Dean Vigoren (Vigorator))
fxmaster 3.5.0 (Johannes Loher (ghost), Emmanuel Ruaud (U~man))
hidden-entity-links 1.1.5 (Erceron, p4535992)
illandril-token-hud-scale 2.1.3 (Joe Spandrusyszyn (illandril))
introduce-me 0.9.5.1 (HarryBoy)
italian-modules-language-pack 0.10 (Simone)
item-delete-check 10.0.2 (tposney)
itemacro 1.8.0 (Kekilla#7036, honeybadger#2614)
items-with-spells-5e 1.0.5 (Andrew Krigline)
lib-wrapper 1.12.10.0 (Rui Pinheiro)
lmrtfy 3.0.3 (VTT Lair)
midi-qol 10.0.15 (tposney)
minimal-ui 1.5.0 (Saif Addin Ellafi)
mmm 1.0.3 (theripper93)
module-credits 2.1.5 (Mouse0270)
monks-active-tiles 10.3 (IronMonk)
monks-enhanced-journal 10.3 (IronMonk)
monks-little-details 10.3 (IronMonk)
monks-player-settings 1.0.6 (IronMonk)
monks-scene-navigation 10.2 (IronMonk)
monks-shops 1.0.2 (IronMonk)
monks-sound-enhancements 1.0.4 (IronMonk)
monks-tokenbar 10.2 (IronMonk)
multi-token-edit 1.24.0 (Aedif)
multiple-document-selection 1.0.6 (IronMonk)
narrator-tools 0.76 (elizeuangelo)
npc-generator-dnd5e 1.13 (Mad Wizard)
pdf-pager 0.27.0 (Farling)
perfect-vision 4.0.32 (dev7355608)
permission_viewer 0.10.0 (Malekal, Kakaroto, Dor)
pin-cushion 1.8.10 (Cole Schultz, Kandashi, ghost, Evan Clarke, Ethaks, p4535992)
popout 2.9 (KaKaRoTo, Posnet)
qol-maximize-reopened-sheets 1.0.4 (shemetz)
quickscale 1.6.1 (unsoluble)
rest-recovery 1.3.6 (Wasp)
sequencer 2.3.12 (Wasp)
share-media 0.0.37 (DarKDinDoN)
smarttarget 0.9.4 (theripper93)
socketlib 1.0.12 (Manuel Vögele)
statuscounter 2.0.15 (Adrian Haberecht)
tagger 1.3.8 (Wasp)
tidy5e-sheet 0.6.6 (sednec#3813)
times-up 10.0.2 (tposney)
token-action-hud 3.0.12 (Larkinabout, Drental, ^ and stick)
token-auras 2.1 (Kim Mantas)
token-z 0.7.6 (theripper93)
tokenmagic 0.6.1.2 (SecretFire, sPOiDar, Zimm, Lozalojo, Moerill, KLO, dev7355608, Mestre Digital, BrotherSharper-Touge, OsiJr)
tokenmagic-automatic-wounds 1.0.8 (shem)
translation-core-it 0.31 (Simone)
translation-dnd5e-it 0.50 (ariakas81, Simone, MrDaerlic, ciuei, DMage, Floppy, heirold, Elia.Hard)
user-latency 1.3.8 (hypnoCode)
visual-active-effects 10.0.3 (Zhell)
warpgate 1.14.0 (honeybadger)
zoom-pan-options 1.8.4 (shemetz)

**Comment by sneat** [comment]
Hi @p4535992 I would have expected there to be another error above that one saying which module and key.

`Copy Environment | Could not export settings for ${v.namespace}.${v.key} due to an error. Please report this as an issue on GitHub.`

Looking at the code though, I can see that even though it has the error, it then still tries to include it in the export (triggering the error you're seeing). I'll make that adjustment to exclude those that fail - it should be telling you which one/s though.

Would you mind trying v2.1.6 which you can download the zip from the green Code button up the top right of https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/tree/2.1.6 and let me know if that helps you?

You can also reach out to me on discord at `blair#9056`

**Comment by p4535992** [comment]
Yea you are right me stupid the module was https://github.com/etriebe/dnd-randomizer i will contact the developer about it.

**Comment by sneat** [comment]
@p4535992 I've released v2.1.6 which should let you export and import the settings, even though that module's setting is invalid in v10.
