### ISSUE TITLE
[Feature Request] Copy playlist, macro, and hotbar settings.

### ISSUE THREAD

**Issue by tehguitarist** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#37]
Title says it all really.

The hotbar is probably the lowest hanging fruit because it already exists in the users.db, but does rely on ID's from Macro.db. Macro.db has flags for things like "last edited by" so not sure what ramifications that would have (if any). There might end up being ID's referenced for permissions that don't exist anymore.

 Playlists, I guess could be an easy one, as it would just be grabbing the entire contents, creating a new playlists.db if needed, and then pasting it in there.

That said, I'm not sure how the module grabs the data, so this might actually be more complicated than a first pass look, I tried to poke around a bit, but couldn't see anything that obviously accessed the files directly (which isn't a bad thing).

I think that this would more or less complete out the complete "take settings from one world to another".

**Comment by sneat** [comment]
Playlist and Macro documents are their own type and are better suited being exported via something like the `Adventure` document format (via something like a shared compendium).

**Comment by tehguitarist** [comment]
Understood! I think I agree on the Playlist and Macro level. 
I guess my thinking is that there's just no good way to get user macro loadouts across worlds easily, as they tend to link to UUIDs, thus the macro settings. That said, it's not the end of the world having to log into each user and set them up one by one, just a bit time consuming. Less about moving Macros, more about the user set ups if that makes sense, but I'll have to look into the Adventure document format in case hotbar loadouts can be included!

**Comment by sneat** [comment]
Yeh, that makes sense. I don’t have a good solution for you unfortunately. I thought there was a module ages ago that let you set up players hot bars (similar to the player settings module), but I can’t find it now. 

The adventure document format won’t help you for that though, it’s just a convenient way to move things between worlds.

**Comment by tehguitarist** [comment]
That's fair enough. If I get the time to research how, I might even have a crack at making my own, though the new v11 database might make that more challenging. Thanks for your input!
