### ISSUE TITLE
[BUG] After import, all compendiums moved out of folder structure

### ISSUE THREAD

**Issue by DoubleKing-Prime** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#41]
**Describe the bug**
After importing settings from another world, all compendiums (system compendiums and otherwise) are removed from the folders they used to be organized in, and put into the root compendium menu

**To Reproduce**
1. Export settings from a world
2. Create a new world (Pathfinder 2e)
3. Install modules (including this one)
4. Import settings
5. Check compendium menu

**Expected behavior**
No change to the organization of the compendiums in their folder structure

**Screenshots**

**Browser:**
 Chrome v114.0.5735.134

**Foundry Version:** 
Version 11 Stable Build 305

**System:** 
Pathfinder 2e

**Additional context**

**Comment by sneat** [comment]
Thanks @Osodelnieve 

Have updated this in v2.1.8 to exclude that option. If you're importing existing settings, you can uncheck the `core.compendiumConfiguration` setting which will prevent the folder assignment being broken (what's happening is the Folder IDs are different between the worlds, so they are being set to invalid IDs).

![image](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/assets/293277/91fce1e1-2d37-4a90-9d01-a808522778ee)

**Comment by DoubleKing-Prime** [comment]
Awesome! 

That looks to have resolved it in 2.1.8. Thanks for the quick reply/work, @sneat !

**Comment by sneat** [comment]
@Osodelnieve sorry to bring this one back up, but would you be able to test v2.2.0 for me (which isn't released yet). I'm trying to re-add support for the compendium folder structure exports, but also not breaking the PF2e default folders that are used. https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/issues/45#issuecomment-1657759102

**Comment by DoubleKing-Prime** [comment]
Just tried it out. That seems to still keep the PF2e folders intact!

Quick question: since I installed the unreleased version, once the new version is released, I should just update normally right? Thanks!

**Comment by sneat** [comment]
Thanks for that @Osodelnieve 👍

As for your question, you already have 2.2.0 so it won’t update, but it will update as normal to 2.2.1 going forward.
