### ISSUE TITLE
[BUG] Sufficiently large settings breaks foundry?

### ISSUE THREAD

**Issue by esheyw** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#43]
**Describe the bug**
just tried to move my settings between one world and another. exported, logged out, started the other world, enabled FCE, selected just-created json for import and... : ![](https://i.imgur.com/0Yskh5w.png)

**To Reproduce**
Install this list of modules: 
### Active Modules
Actor Link Indicator v0.2.0
Advanced Drawing Tools v2.0.11 [Bugs URL](https://github.com/dev7355608/advanced-drawing-tools/issues)
Always HP v11.04 [Bugs URL](https://github.com/ironmonk88/always-hp/issues)
Are You Focused? v1.2.3
Automated Animations v4.2.61
Better Entity Link v1.2.3.1
Button Feel vv1.1.2
Chat Images v3.2
Cleaner sheet title bar v1.5.1
Combat HP Display v1.2.1
Connection Monitor v1.4.0
Core Settings Expanded v1.4.0 [Bugs URL](https://gitlab.com/geekswordsman/core-settings-expanded/-/issues)
Cosmic Dice v1.0.1
Covered Token Rescue HUD v1.0.11
Default Button Visibility v10.273.1
Designer Doors v3.1.1 [Bugs URL](https://www.github.com/exitalterego/designerdoors/issues)
DFreds Droppables v3.0.1 [Bugs URL](https://github.com/DFreds/dfreds-droppables/issues)
Dice So Nice! v4.6.8 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
Dice Stats v1.13.1
Dig Down - Advanced Search v2.7.3
Disable Mouse Wheel Control for Sliders v2.0.0
Drag Ruler v1.13.8 [Bugs URL](https://github.com/manuelVo/foundryvtt-drag-ruler/issues)
Entice with Dice so Nice v0.1.0
esheyw Local Transfer Module v1.3.0
Find the culprit v1.4.6 [Bugs URL](https://github.com/Moerill/fvtt-find-the-culprit/issues)
Force Client Controls v1.0.4 [Bugs URL](https://gitlab.com/kimitsu_desu/force-client-controls/-/issues)
Force Client Settings v2.3.2 [Bugs URL](https://gitlab.com/kimitsu_desu/force-client-settings/-/issues)
Forien's Copy Environment vv2.1.8 [Bugs URL](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/issues)
Foundry Summons v1.4.1 [Bugs URL](https://github.com/mrvauxs/foundry-summons/issues)
Foundry VTT Anniversary Dice Set by The Rollsmith v1.0.1 [Bugs URL](https://therollsmith.com/contact/)
FXMaster v4.0.2 [Bugs URL](https://github.com/ghost-fvtt/fxmaster/issues)
GM Vision v1.0.3 [Bugs URL](https://github.com/dev7355608/gm-vision/issues)
Hey, Wait! v0.7.5
Hide GM Rolls v0.15.3 [Bugs URL](https://github.com/sPOiDar/fvtt-module-hide-gm-rolls/issues)
Improved Macro Editor v10.1 [Bugs URL](https://github.com/teroparvinen/foundry-improved-macro-editor/issues)
Item Piles v2.7.1 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues)
JB2A - Free Extra Assets v0.0.1
JB2A - Patreon Complete Collection v0.5.9
Layer Hotkeys v2.4.1
lib Themer v1.0.7 [Bugs URL](https://github.com/mouse0270/lib-themer/issues)
libWrapper v1.12.12.1 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
Lordu's Custom Dice for Dice So Nice v0.39
Mass Edit v1.43.8
Melvin's Mechanical Masterworks v2.4.0
Module Management+ v2.2.3 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Combat Details v11.03 [Bugs URL](https://github.com/ironmonk88/monks-combat-details/issues)
Monk's Combat Marker v11.01 [Bugs URL](https://github.com/ironmonk88/monks-combat-marker/issues)
Monk's Hotbar Expansion v10.1 [Bugs URL](https://github.com/ironmonk88/hotbar-expansion/issues)
Monk's Little Details v11.03 [Bugs URL](https://github.com/ironmonk88/monks-little-details/issues)
Monk's TokenBar v11.01 [Bugs URL](https://github.com/ironmonk88/monks-tokenbar/issues)
Monk's Wall Enhancement v11.01 [Bugs URL](https://github.com/ironmonk88/monks-wall-enhancement/issues)
Ownership Viewer v11.1 [Bugs URL](https://github.com/mclemente/fvtt-module-permission-viewer/issues)
Party Overview v2.16.1 [Bugs URL](http://github.com/mclemente/party-overview/issues)
Pathfinder 2e: Abomination Vaults v3.0.0
Pathfinder Token Pack: Bestiaries v1.0.6
PDF to Foundry Importer v4.0.0
PF2e Alignment Damage and Other Immunities v1.2.1 [Bugs URL](https://github.com/Fin-bar/Pf2e-Alignment-Damage/issues)
PF2e Animations v2.16.4
PF2e a shopping experience v3.0.0
PF2e Companion Compendia v5.8
PF2e Dailies v2.9.1 [Bugs URL](https://github.com/reonZ/pf2e-dailies/issues)
PF2e Dorako UI v2.2.5 [Bugs URL](https://github.com/Dorako/pf2e-dorako-ui/issues)
PF2e Drag Ruler Integration v3.0.3
PF2e Effect Description v1.5.0 [Bugs URL](https://github.com/reonZ/pf2e-effect-description/issues)
PF2e Exploration Activities v1.2.1
PF2E Exploration Effects v3.0.0
pf2E Extempore Effects v1.7.3 [Bugs URL](https://github.com/shemetz/pf2e-extempore-effects/issues)
PF2e Flat Check v1.7.0 [Bugs URL](https://github.com/jessev14/pf2-flat-check/issues)
PF2e Giveth v1.4.0 [Bugs URL](https://github.com/reonZ/pf2e-giveth/issues)
PF2e Iconic Adventurers v1.2.3
PF2e Interactive Token Tooltip v1.28.2 [Bugs URL](https://github.com/reonZ/pf2e-token-hud/issues)
PF2e Keybind Menagerie v5.0.0
Pf2E Modifiers Matter v1.7.7 [Bugs URL](https://github.com/shemetz/pf2e-modifiers-matter/issues)
PF2e Ranged Combat v4.0.2 [Bugs URL](https://github.com/JDCalvert/FVTT-PF2e-Ranged-Combat/issues)
PF2e Reaction Checker v0.2.17 [Bugs URL](https://github.com/reyzor1991/foundry-vtt-pf2e-reaction/issues)
PF2e Rules-Based NPC Vision v2.0.1 [Bugs URL](https://github.com/JDCalvert/FVTT-PF2e-Rules-Based-NPC-Vision/issues)
pF2e See Simple Scale Statistics v1.3.3 [Bugs URL](https://github.com/shemetz/pf2e-see-simple-scale-statistics/issues)
PF2e Spells Summary v1.6.0 [Bugs URL](https://github.com/reonZ/pf2e-spells-summary/issues)
PF2e Stances v1.6.1 [Bugs URL](https://github.com/reonZ/pf2e-stances/issues)
PF2e Staves v1.3.1
PF2e Target Damage v2.4.13 [Bugs URL](https://github.com/MrVauxs/PF2e-Target-Damage/issues)
PF2E Token Markers v2.3.4
PF2e Workbench v5.7.2 [Bugs URL](https://github.com/xdy/xdy-pf2e-workbench/issues)
Polyglot v1.9.4 [Bugs URL](https://github.com/League-of-Foundry-Developers/fvtt-module-polyglot/issues)
Quick Insert - Search Widget v2.8.3 [Bugs URL](https://gitlab.com/fvtt-modules-lab/quick-insert/-/issues)
QuickScale v1.6.4 [Bugs URL](https://github.com/unsoluble/quickscale/issues)
Remote Highlight UI v1.2.2 [Bugs URL](https://github.com/shemetz/remote-highlight-ui/issues)
Reset Movement v1.5.1
Roll Mode Keybindings v1.0.0 [Bugs URL](https://github.com/WesBelmont/rollmode-toggle/issues)
routinglib v1.1.0 [Bugs URL](https://github.com/manuelVo/foundryvtt-routinglib/issues)
Sequencer v3.1.1 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues)
Show Notes v11.2
Sidebar and Windows Resizer v0.7.0
Sidebar Macros v0.8.3 [Bugs URL](https://github.com/arcanistzed/sidebar-macros/issues/new/choose)
Silence Compatibility Warnings v11.0.0 [Bugs URL](https://github.com/dor-fvtt-released-modules/silence-compatibility-warnings/issues)
Simple Calendar v2.3.13 [Bugs URL](https://github.com/vigoren/foundryvtt-simple-calendar/issues)
SmallTime v1.16.6 [Bugs URL](https://github.com/unsoluble/smalltime/issues)
Smart Doors v1.4.1 [Bugs URL](https://github.com/manuelVo/foundryvtt-smart-doors/issues)
Smart Target v1.0.1 [Bugs URL](https://github.com/theripper93/Smart-Target/issues)
socketlib v1.0.13 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
SoundFx Library v1.0.2
Stairways (Teleporter) v0.10.2 [Bugs URL](https://gitlab.com/SWW13/foundryvtt-stairways/issues)
Status Halo v0.1.1
Subfolder Indent v1.0.7
Token Frames v1.5.2 [Bugs URL](https://github.com/yorkshirelandscape/token_frames/issues)
Tokenizer v4.2.4
Token Magic FX v0.6.4
User Latency v2.0.2 [Bugs URL](https://github.com/mawburn/foundry-user-latency/issues)
Warp Gate v1.17.2
WTF: What the Flag? v1.0.3
Zoom/Pan Options v1.10.0 [Bugs URL](https://github.com/shemetz/ZoomPanOptions/issues)
zSync v0.0.8

Then attempt to import this settings file:
[foundry-settings-export-2023-07-16-17-36-46-av19.zip](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/files/12065456/foundry-settings-export-2023-07-16-17-36-46-av19.zip)

**Browser:**
 - chrome latest

**Foundry Version:** 
11.305
**System:** 
pf2e 5.1.2

**Comment by sneat** [comment]
jQuery just doesn't want to parse that much data :( I'll see what I can adjust for you @esheyw

**Comment by sneat** [comment]
@esheyw I've just release v2.1.9 which should fix this issue. Let me know how you go.

**Comment by esheyw** [comment]
Success! Thanks, that did it.
