### ISSUE TITLE
Include Compendium Folder structure  and Compendium settings to the copied settings on v11 please!

### ISSUE THREAD

**Issue by Nedrapter** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#45]
Prior to v11, there was Compendium Folder module which worked well with this module to transfer your compendium folder structure from one world to another. Now on v11 with CF module being a core feature, Copy Environment does not pick up the folder structure... 

On top of that compendium permissions & settings are also now not saved, with compendiums relying on core foundry...

**Comment by sneat** [comment]
The folder functionality was removed as part of the #41 issue. I'll have a think on an appropriate way to handle both situations.

**Comment by Nedrapter** [comment]
I hope you roll well in your investigation!!
Having 100+ compendiums and 10+ worlds, not being able to copy the folder structure and their settings is driving me insane...and then future changes to have to be applied individually on each world...
I would have waited more before updating to v11 if I knew such issues existed...so you're my only hope now of not going insane ^^

**Comment by sneat** [comment]
@Nedrapter are you able to try [v2.2.0](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/tree/2.2.0) for me? You can download a copy of the v2.2.0 release by clicking on the green "Code" button near the top right, and choosing "Download ZIP". Extract that and replace your existing `forien-copy-environment` folder.

You'll likely need to export the settings again for it to also export the associated folder data needed (although I'd be interested to know if it works for you without doing a re-export).

Let me know how it goes for you.

**Comment by Nedrapter** [comment]
> @Nedrapter are you able to try [v2.2.0](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/tree/2.2.0) for me? You can download a copy of the v2.2.0 release by clicking on the green "Code" button near the top right, and choosing "Download ZIP". Extract that and replace your existing `forien-copy-environment` folder.
> 
> You'll likely need to export the settings again for it to also export the associated folder data needed (although I'd be interested to know if it works for you without doing a re-export).
> 
> Let me know how it goes for you.
I'm not sure if I could do it it correctly, as I'm using the Forge hosting service. I uninstalled 2.1.9, then imported the zip folder. Their compendium wizard recognized it as module and I unchecked the "install from Bazaar". However the version still showed 2.1.9 . Idk if it was just the name or it was pulling the 2.1.9 from their Bazaar. Then I proceeded to export and import settings but there was no compendium folder structure change, not changes to compendium settings.

**Comment by sneat** [comment]
Hmm @Nedrapter - I was able to upload the `foundryvtt-forien-copy-environment-2.2.0.zip` file to the forge using the "Summon Import Wizard", unticking the "Install from Bazaar" box (as you say) and it correctly listed the module as v2.2.0.

Are you able to try one more time?

**Comment by Nedrapter** [comment]
I've repeated the process again. Both in the Forge interface and inside the game the module lists as 2.1.9. However in the Forge's bazaar interface it shows the "Update" button. Then I attempted to copy a world's settings (one with organized compendiums and a folder structure) to another world that is a total mess in terms of organization (but still has the same compendium modules):  The new world's compendium settings remain the same and their folder structure a mess.
![image](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/assets/74311190/c979630c-5143-4bcf-915a-c3f86cea3e92)
![image](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/assets/74311190/d38366bc-5f6a-408c-83d9-860ff2a9d551)

**Comment by sneat** [comment]
@Nedrapter can you confirm that the drop down in the top left says `2.2.0` instead of `master`? The version number that you're getting is consistent with the `master` branch, rather than the [2.2.0 branch](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/tree/2.2.0).

![image](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/assets/293277/ea5199f1-8fbd-4e75-b642-b29a28466763)

**Comment by Nedrapter** [comment]
That was the issue...I didn't know what that dropdown was doing!
I can report that 2.2.0 is a success!! Both folder structure and permissions are being copied!
Can I ask which setting is it in the import list? (So I can copy only that)

**Comment by sneat** [comment]
@Nedrapter perfect! It's the `core.compendiumConfiguration` setting.
