### ISSUE TITLE
[BUG] Not turning modules back on

### ISSUE THREAD

**Issue by ksignorini** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#49]
When importing saved settings, the modules that the settings are for do not turn back on anymore. This was the best feature of the module.

**Comment by sneat** [comment]
Has this just started happening for you @ksignorini 

I'll try have a look at it this week.

**Comment by sneat** [comment]
I just did a quick test in Foundry v11.315 with dnd5e 3.0.4 and importing the previously exported settings enabled the previously enabled modules successfully.

Do you see any errors in the Console (usually F12) when you try to import?

**Comment by ksignorini** [comment]
No, no errors at all.

**Comment by sneat** [comment]
What version of foundry are you on?

Would you be willing to send me a copy of the json you're trying to load? If you're on discord you can ping me at `blair9056`, otherwise attach to here or something?

**Comment by Crowguard** [comment]
Also running into this issue tonight. No errors in the console. Feel free to DM me on Discord; `crow_guard`

Edit: I am 99% certain this is a Forge issue for myself now; the same settings import properly on the electron app, but fail to activate any modules when importing on Forge.

Foundry 12.331
Forge

[foundry-settings-export-2024-11-04-21-26-09-gatewalkers.zip](https://github.com/user-attachments/files/17626690/foundry-settings-export-2024-11-04-21-26-09-gatewalkers.zip)

**Comment by Crowguard** [comment]
@ksignorini Any chance you're on Forge?

**Comment by sneat** [comment]
Thanks for the update @Crowguard - will test it on the Forge over the next few days when I get a chance.
