### ISSUE TITLE
[BUG] Cannot destructure property of 'pack' of 'n' as it is undefined

### ISSUE THREAD

**Issue by git-kor-av** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#50]
I have exported settings from my PF2 base world configuration, try to import this error appears and then the module restarts foundry so I can't get more information.

This is on Foundry v12.328 with PF2 6.0.4.  Attached is the file I've been trying to import, as well as the error I was able to capture:
![image](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/assets/32276185/cfff7552-4ea5-43ea-b7af-b8ef658732e6)
[foundry-settings-export-2024-07-03-14-11-17-pf2-base-setup.json](https://github.com/user-attachments/files/16089635/foundry-settings-export-2024-07-03-14-11-17-pf2-base-setup.json)

**Comment by git-kor-av** [comment]
I was able to get the following expanded error:
![image](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/assets/32276185/f893ac57-1b90-406d-b026-94a710807c9d)

**Comment by sneat** [comment]
Fixed in [Release v2.2.1](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/releases/tag/v2.2.1)

Thanks
