### ISSUE TITLE
[BUG] I think this mod copies over the World Calendar date between worlds, which surprised me

### ISSUE THREAD

**Issue by ronaldsf1977** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#53]
I run several Worlds in Pathfinder 2e. When I copy my settings from one World to another using this mod, it seems to replicate the date in the World Calendar from the previous World to the new World. 
I was hoping that this could be excluded as the default behavior.

Using Foundry v12, Build 327
Pathfinder 2nd Edition 6.0.4

Thanks for your work!

**Comment by sneat** [comment]
@ronaldsf1977 it copies across all settings (as it copies the whole environment). In the dialog that appears, you can deselect options, so you should be able to scroll down to the setting for the calendar and untick it and it won't be copied across.

**Comment by ronaldsf1977** [comment]
Thanks, though this is more an FYI that I think this is something that should be defaulted to off, if possible.
Because once the deed is done, I don't have a record of what the date used to be.

**Comment by sneat** [comment]
That's fair enough @ronaldsf1977 - I'll make the adjustment.

**Comment by sneat** [comment]
Feature added in v2.2.2 @ronaldsf1977 

Given you have run it previously, you will either need to:
1. Unselect the following two options when you import next:
    - `core.time`
    - `pf2e.worldClock.worldCreatedOn` 
3. Run `game.settings.set('forien-copy-environment', 'selected-properties', undefined);` as a script macro to reset to the default (unselecting those two options).

**Comment by ronaldsf1977** [comment]
> Feature added in v2.2.2 @ronaldsf1977
> 
> Given you have run it previously, you will either need to:
> 
> 1. Unselect the following two options when you import next:
>    
>    * `core.time`
>    * `pf2e.worldClock.worldCreatedOn`
> 2. Run `game.settings.set('forien-copy-environment', 'selected-properties', undefined);` as a script macro to reset to the default (unselecting those two options).

I only need to do this if I am relying on an exported JSON from before the latest patch, correct? So, if I make a new export post-patch, I don't need to worry about this?
