### ISSUE TITLE
[BUG] Silent Fail on Import Attempt

### ISSUE THREAD

**Issue by TheMook** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#6]
**Describe the bug**
When attempting to import a previously exported .json file, Forien's Copy Environment silently fails and imports no settings, even if it is the only Module enabled.

**To Reproduce**
1. Right-click under General Information while in FoundryVTT in the world to copy settings from. choose "Export Settings."
2. Return to Setup, Create New World.
3) Once inside FoundryVTT in the world to copy settings to, choose "Import Settings." The settings are not imported and no error message is generated.

**Expected behavior**
Expected all settings to be Imported from a previous Export (both occurred within minutes of one another, using the same/latest version, 2.0.4)

**Screenshots**
Attached is the dev console when attempting Import (I tried twice in a row in the screenshot)
![forien01](https://user-images.githubusercontent.com/3688589/121750381-24cf5b00-cac1-11eb-9082-153f0d3cbfc7.JPG)

**Browser:**
 Chrome

**Foundry Version:** 
0.8.6

**System:** 
Win 10

**Additional context**
I have *numerous* Modules I'm transferring settings for, but when attempting Import the only active Module is Forien's Copy Environment.

Thanks!

**Comment by TheMook** [comment]
Oops, forgot -- here is the exported .json (zipped) as well.
[foundry-settings-export_06-11-2021.zip](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/files/6641499/foundry-settings-export_06-11-2021.zip)

**Comment by jacksands** [comment]
same here, but deactivating all modules except foriens and trying again solved...

**Comment by sneat** [comment]
Fixed in v2.0.5
