### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dmulatinho** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#9]
**Describe the bug**
Nothing happens when i import settings

**To Reproduce**
1. Go to 'game settings'
2. Click on 'import settings'
3. Import "foundry-settings-export"
4. Click in 'Import Settings'

**Expected behavior**
The import windows appears and when i'm click to 'Import Settings', nothing happens

**Screenshots**
![Captura de Tela (88)](https://user-images.githubusercontent.com/40870044/121787975-ebb9e800-cb9f-11eb-923b-0936a058f5a9.png)

**Browser:**
Mozila Firefox

**Foundry Version:** 
0.8.6

**System:** 
Node

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by Maselkov** [comment]
#8 should fix it

**Comment by dmulatinho** [comment]
I've tried here and nothing happened again =/

**Comment by TheMook** [comment]
(same in Chrome, per https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/issues/6)

**Comment by Avitale34** [comment]
Same here

**Comment by sneat** [comment]
Fixed in v2.0.5
